env:
  es2021: true
extends:
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules: {
  "@typescript-eslint/indent": ["error", 4],
  "@typescript-eslint/explicit-member-accessibility": "error"
}