version: '3.4'

services:
  shop:
    image: shop
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DB_URI: mongodb://user:pass@mongodb/?authSource=admin
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src/
        read_only: true

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=shop
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
