version: '3.4'

services:
  mongodb:
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_DATABASE=shop
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
