version: '3.4'

services:
  shop-server:
    image: shop-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_URI: mongodb://user:pass@mongodb/?authSource=admin
    ports:
      - 3001:3000

  mongodb:
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_DATABASE=shop
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
