version: '3.4'

services:
  shop-server-dev:
    image: shop-server-dev
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    environment:
      NODE_ENV: development
      DB_URI: mongodb://user:pass@mongodb/shop?authSource=admin
    volumes:
      - ../src:/usr/src/app/src/
      - ../package.json:/usr/src/app/package.json
      - ../package-lock.json:/usr/src/app/package-lock.json
      - ../tsconfig.json:/usr/src/app/tsconfig.json
    command: /bin/sh -c "while sleep 1000; do :; done"

  mongodb:
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_DATABASE=shop
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ../data/db:/data/db
      - ../data/configdb:/data/configdb
